dist: trusty
sudo: true

language: d

d:
  - dmd

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install make build-essential pkg-config libtool autoconf automake gettext libevent-dev libssl-dev -y

install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.1/doveralls_linux_travis"

script: ./travis-ci.sh
